### ISSUE TITLE
[FEATURE REQUEST] Upgrade to Python 3

### ISSUE THREAD

**Issue by CBenghi** [litrl/litrl_code#19]
**Describe the issue**
Executing the installation command we get notified that Python 2.7 is reaching end of life support in January 2020, less than an year.

"DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7."
Pip also notified that version 2.7 is not going to be maintained.

**Expected behavior**
Research software that can be usefully picked up by other teams should be reliable for longer than that timespan.

**Additional context**
Would it be complex to update the installation to a current version of Python, with longer support?

**Comment by CBenghi** [comment]
Please note that I did not mean to mark this as a bug, but that was done by the template.
I'm not sure how to remove the "bug" label.

**Comment by brogly-zz** [comment]
@CBenghi - Thanks for bringing this up - I was going to add this myself at some point - I have added this to the next milestone. It is unclear to me how much effort this would require; it could be minimal or it may take a while to move everything over. In any case, we will work to complete this before 2.7 is outdated. If you think it should be done for JOSS, I can work on that but our capacity for significant changes is limited right now.

**Comment by CBenghi** [comment]
@brogly, 
In principle I've added it w/reg Joss, but I'm not sure about the policy for this.
I appreciate that it could be non trivial, but I'm not much familiar with python.

I'll have to speak to the editor about that.

**Comment by brogly-zz** [comment]
@CBenghi If it is a blocker to publication, we will address it. The problem is that we really don't have the capacity for the upgrade right now... we would prefer to do it in the coming months. Anyways, let me know.

**Comment by brogly-zz** [comment]
@CBenghi @lrasmus @danielskatz Have upgraded to Python 3.6.8. We are locked at this version for now due to the dependency on Pattern which only supports Python 3.6 out of the box. Also, 3.6.8 is the latest version PSF provides a Windows installer for, so I have suggested in another issue that re-writing the detectors in ML.NET in C# would be a nice to have since everything could be done in Visual Studio and we wouldn't have Python dependency issues anymore (we plan on bringing in some new students to upgrade this by next year and I hope they can complete a full C# re-write... in addition to improving things in general). In the meantime, will continue to monitor Pattern for when it receives support for newer versions of Python and upgrade accordingly which should now be straightforward since everything is Python 3 now. Have opened another issue for that.
